debug: false
#
# 数据库设置，选择你需要使用的数据储存方式，sqlite,mysql
# 默认: sqlite
data_storage:
  use_type: sqlite
  mysql:
    host: '127.0.0.1'
    port: 3306
    database: 'server_Mail'
    username: 'root'
    password: '123456'
    params: '?autoReconnect=true&useSSL=false'
  hikari_settings:
    maximum_pool_size: 10
    minimum_idle: 10
    maximum_lifetime: 1800000
    keepalive_time: 0
    connection_timeout: 5000
SmtpSet:
  start: false
  account: '****r@163.com' # 发件账号
  password: '*********' # smtp服务器授权码
  personal: 'GeekMail-高级邮件系统' # 发件人信息
  subjects: 'GeekMail-收件提醒' # 邮件标题
  host: 'smtp.163.com' # smtp服务器
  port: '25' # 端口

config:
  # 期限设置，如果使用，邮件到期将自动删除
  use_bundle: false # 物品邮件，物品预览使用lore展示 (只限 1.17+)
  Expiry:
    use: true
    # 邮件默认到期时间
    time: 2d
    # 数据维护任务时间 单位 秒
    auto: 600

# 邮件种类显示名称转换
MailType:
  MONEY_MAIL:
    tag: "&e金币"
  POINTS_MAIL:
    tag: "&b点券"
  EXP_MAIL:
    tag: "&a经验"
  TEXT_MAIL:
    tag: "&f文本"
  CMD_MAIL:
    tag: "&6指令包"
  ITEM_MAIL:
    tag: "&6物品"

    
