
name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup jdk 8.0
        uses: actions/setup-java@v2
        with:
          java-version: 8

      - name: cache gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-build-${{ env.cache-name }}


      - name: 授予 gradlew 的执行权限
        run: chmod +x ./gradlew

      - name: 使用 Gradle 构建
        run: ./gradlew clean build

      - name: 上传工件
        uses: actions/upload-artifact@v2
        with:
          name: GeekMail-Pro Artifact
          path: build/libs/*.jar
